services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/code/app
      - ./backend/data:/code/data
    working_dir: /code
    environment:
      - ENV=development
    networks:
      - shared-network

networks:
  shared-network:
    name: shared-network
